version: "3.9"
services:
  nestjs:
    container_name: blackbot-nestjs-app
    build: docker/dev
    env_file: 
      - .env
    ports: 
      - "3000:3000"
    volumes: 
      - .:/server
    links: 
      - mongodb
  mongodb:
    container_name: blackbot-mongodb
    image: mongo:latest
    restart: always
    ports: 
     - "27017:27017"
