version: "3.9"
services:
  nestjs:
    container_name: blackbot-nestjs-app
    build: .
    ports: 
      - "80:3000"
  mongodb:
    image: mongo:latest
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: blackbot
